### ISSUE TITLE
[FR] Run as daemon without exposing console on Win32

### ISSUE THREAD

**Issue by Kein** [shadowsocks/go-shadowsocks2#195]
By default, when starting `go-shadowsocks2` it will load condrv and display console, always. For a proxy-client mode this makes no sense. Yes, there are some hacky workarounds how to run consle app on Windows hidden, but in reality this is something shadowsocks client should to do by itself. 

1. There is no need to display console when you have no plans to debug the issues or keep a log
2. There is no reason to spawn conhost session in this case as well.

Something like `-headless` would be nice to have - run it normally, old way by default, and when flag supplied run it daemon-like.

**Comment by riobard** [comment]
If anyone knows how to do it, please send a Pull Request.

**Comment by dev4u** [comment]
参考一下这个做法：
https://github.com/shadowsocks/shadowsocks-rust/issues/333#issuecomment-739316992

**Comment by riobard** [comment]
@dev4u  Thanks for the info! Looks like a distribution and packaging problem. Since we do not provide any system-specific packaging, if someone is interested in this, please do it in another repo.

**Comment by Kein** [comment]
That comment bears no relevance to the issue? Why did you close it?

**Comment by riobard** [comment]
Because it's clearly a packaging issue to properly run as a service on Windows and we do not provide any packaging support, same as we do not provide `systemd` service definition for Linux.

**Comment by riobard** [comment]
> No it isnt? He posted some nonsense about using some 3rd party tools. With the same success he could post 3rd party tools for format your hard drive - **what relevance do they have**?
> Dnscrypt proxy run just fine in background. There are other programs that dont even use the same approach as dnscrypt and they can start in background. It has nothing to do with bootleg attempts to do it via some dumb means.

Let me be very clear: we do not provide any packaging or service runtime support for any operating system. The failure of Windows not providing built-in user-friendly tool to manage services is Microsoft's problem. If you're unhappy about it, go complain it to them, or do the hard work of implementing it yourself if you do not trust 3rd-party service management tools.

> What is exactly your issue, you've already added a tag `help wanted`. Is extra issue in the list of issue wont let you sleep or something? It is like you were waiting for any kind of nonsensical reason to close it. Let someone else handle it if they stumble upon it, nobody is forcing you.

What's your problem? I wrote the majority of the code and did most of the maintenance work here for free. Instead of expressing gratitude for my and other contributors' work and convincing me the necessity of your request, you're here bitching and whining simply because I don't agree with how you would like it to work.

Again let me remind you that this is open source. Fork it to do whatever you want and just follow the very relax license agreement.

**Comment by riobard** [comment]
> So what the issue leaving it open for someone to pick up and contribute later at some point? Not so open after all? We clearly need more forks instead of less ego-centric maintainers. May be someone with the knowledge could have stumbled upon this issue and fix it in few minutes flat but he wont anymore. That's my problem.

Because it is me that will spend the time to review the code change and maintain it in the future, and I decide it's neither a good idea nor in the best interest of this project to accept that change? What misconception of open source do you have in mind?

Your problem is that you feel you're entitled to enjoy other people's work for free and demand whatever you want. I'm sorry to tell you the world does not work that way. Either you explain very politely to convince me it's a good idea (which I disagree), or you pay me enough money to buy my time to implement and maintain it (which I doubt you could afford), or you fork this project and convince someone else to contribute to your fork. That is how open source works.

**Comment by Kein** [comment]
> Because it is me that will spend the time to review the code change and maintain it in the future

Ah I see, you could have said it from the start - _no, the project is not open source because I cant be arsed to maintain it as a proper open-source._

**Comment by Kein** [comment]
Understandable, have a nice day.
