### ISSUE TITLE
[讨论]relay的时候压缩数据是否有意义？

### ISSUE THREAD

**Issue by hikkikuma1991** [shadowsocks/go-shadowsocks2#59]
go官方自带了几种完善的压缩算法，所以在数据relay的时候对数据进行压缩/解压是否有意义？等效于降低线路丢包率？

**Comment by riobard** [comment]
No. 

Compression must be done at the application layer, not at transport layer. E.g. web servers and browsers already negotiate compression in HTTP headers. Encrypted HTTPS streams cannot be compressed by proxies because they are effectively random bytes.

Additionally, compression will not reduce packet loss rate as it's a link layer problem. In fact, compression amplifies the effect of packet loss because a single lost packet will have greater impact.
