### ISSUE TITLE
[Q] Question about the AEAD implementation key's expanding and re-hashing

### ISSUE THREAD

**Issue by arthurkiller** [shadowsocks/go-shadowsocks2#60]
According to the document about AEAD in [shadowsocks.org](https://shadowsocks.org/en/spec/AEAD-Ciphers.html). HKDF_SHA1 is strong enough even if the in put key is weak.

But I get the code in ss-go2 that __hashing and expanding__ the input key to requested key length first, then get the hashed key do the `HKDF_SHA1` again to get the subkey for AEAD.

Why do this? And I can't see the document request for re-hashing & expanding for the key.

Only once HKDF operation is leaking safty?

Thx dude, waiting for reply. 

@riobard

**Comment by riobard** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/42

**Comment by dszhengyu** [comment]
@riobard I have talked with @arthurkiller 
Still, we can't figure out why to expand the user password to the key length before apply the HKDF_SHA1 function 
Nor I can find this mentioned in the document[https://shadowsocks.org/en/spec/AEAD-Ciphers.html](https://shadowsocks.org/en/spec/AEAD-Ciphers.html)

**Comment by riobard** [comment]
Do you mean why we do this? https://github.com/shadowsocks/go-shadowsocks2/blob/3334af5060f377e14a92ef8ebfcd746195700d01/core/cipher.go#L88

Before SIP007 we used the key derived from password directly. SIP007 proposed to compute subkeys from that derived key.

In theory we could compute subkeys from password directly, but why bother? All SS crypto code deal with keys instead of passwords.
